#!/usr/bin/env bash

#for file in `ls`
#do
#    echo ${file}
#    bname=${file:0:9}
#    mname=${file:9:1}
#    aname=${file:0-4}
#    lname=${aname}${mname}${bname}
#    mv ${file} ${lname}
#
#done


for file in `ls`
do
    echo ${file}
    bname=${file%%_*}
    mname=${file:5:1}
    aname=${file##*_}
    lname=${aname}${mname}${bname}
    mv ${file} ${lname}
done
